export const seo = {
  title: "Aashish Timalsina | Laravel & SaaS Engineer — Tutorials & Production Systems",
  description:
    "Laravel and SaaS tutorials from a developer who ships real systems: multi-tenant apps, APIs, Filament admin, eSewa/Khalti payments, and production DevOps. Based in Nepal, working globally.",
  keywords: [
    "Aashish Timalsina",
    "Laravel developer",
    "Laravel SaaS",
    "Laravel tutorial",
    "multi tenant Laravel",
    "Laravel API",
    "Laravel HRM",
    "Filament Laravel",
    "Laravel developer Nepal",
    "SaaS developer",
    "production Laravel",
    "Laravel DevOps",
    "Laravel Next.js",
    "Next.js Laravel tutorial",
    "headless CMS Laravel",
    "MDX blog Next.js",
    "server side SEO Next.js",
    "full stack developer Nepal",
  ],
} as const;
